cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index),
    path('search/', views.search_product, name='search_product'),
    path('product_list', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args=[self.slug])
    

class Brand(models.Model):
    brand = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    
    class Meta:        
        verbose_name = 'brand'
        verbose_name_plural = 'brands'

    def __str__(self):
        return self.brand


class Product(models.Model): 

    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='products',blank=True, null=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    top = models.BooleanField(default=False)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_detail", kwargs={"id": self.id, "slug": self.slug})
    

class Gallery(models.Model):
    images = models.ImageField(upload_to='products/Gallery', blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')

    def __str__(self):
        return self.product.name
    

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, Brand, Gallery
from django.contrib import messages
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator , EmptyPage, PageNotAnInteger 


def index(request):
    category = None
    categories = Category.objects.all()

    products = Product.objects.filter(available=True)

    top = Product.objects.filter(top=1)


    return render(request, 'shop/index.html', context={
        'category': category,
        'categories': categories,
        'products': products,
        'top': top,

    })

def product_list(request, category_slug=None):

    brand = Brand.objects.all()
    brandID = request.GET.get('brand') 

    category = None
    categories = Category.objects.all()
    
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    if brandID:
        products = Product.objects.filter(brand = brandID)
    else:
        Product.objects.all()
    
    paginator = Paginator(products, 6)    
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
        pass

    return render (request, 'shop/product/list.html', context={
        'category': category,
        'categories': categories,
        'products': products,
        'brand': brand,
        'page': page,

    })



def product_detail(request, id, slug):

    category = None
    categories = Category.objects.all()

    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    images = Gallery.objects.filter(product=product)
    return render(request, 'shop/product/detail.html', context={
                                                        'product': product,
                                                        'cart_product_form': cart_product_form,
                                                        'images': images,
                                                        'category': category,
                                                        'categories': categories,
    })



def search_product(request):

    brand = Brand.objects.all()
    brandID = request.GET.get('brand') 

    category = None
    categories = Category.objects.all()

    if brandID:
        products = Product.objects.filter(brand = brandID)
    else:
        Product.objects.all() 
        
    query = request.GET.get("Q")
    products = Product.objects.filter(name__icontains=query)


    

    return render(request, 'shop/product/search.html', context={'products': products,
                                                                'query': query,
                                                                'category': category,
                                                                'categories': categories,
                                                                'brand': brand,                                                            
                                                                })

shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Book Haven{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/core-style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">


</head>
<body>


<!-- Header -->
	<header class="header">
		<div class="header-top">
			<div class="container">
				<div class="row">
					<div class="header-top-left">
						<ul>
							<li><i class="fa fa-home"></i>Київ, Україна</li>
							<li><i class="fa fa-phone"></i>+380 99 999 99 99</li>
							<li><i class="fa fa-calendar"></i>Працюємо без вихідних </li>
						</ul>
					</div><!-- Header top left -->
					<div class="header-top-right pl-5">
						<div class="social-profiles">
							<ul>
								<li><a href="#"><i class="fa-brands fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa-brands fa-instagram"></i></a></li>
								<li><a href="#"><i class="fa-brands fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa-brands fa-telegram"></i></a></li>
							</ul>
						</div><!-- Social profiles -->
						<div class="book-table">
							<a href="/">Book Haven</a>
						</div> <!-- Book a table -->
					</div><!-- Header top Right -->
				</div>
			</div><!-- Container -->
		</div><!-- Header top -->
       <div class="logo-search-area">
			<div class="container">
				<div class="row">
					<div class="col-md-4 col-sm-4">
						<div class="search-box">
							<form class="search-form" action="{% url 'shop:search_product'%}" method="GET">
								<input class="form-control mr-sm-2" type="search" placeholder="Знайти книгу" aria-label="Пошук" name="Q">
								<button type="submit">
									<i class="fa fa-search"></i>
								</button>
							</form><!-- Search form -->
						</div><!-- Search area -->
					</div> 
					<div class="col-md-4 col-sm-4">
						<div class="logo">
							<a href="/"><img src="{% static 'img/logo.png' %}" alt=""></a>
						</div><!-- logo -->
					</div>

					<div class="col-md-4 col-sm-4">
						<div class="cart">
                        {% with total_items=cart|length %}
							<a href="{% url 'cart:cart_detail' %}">
								<i class="fa fa-shopping-cart"></i>
								<span>{{ total_items }}</span>
							</a>
                        {% endwith %}
						</div><!-- cart -->
					</div>
				</div>
			</div><!-- container -->
		</div><!-- Logo and search area -->
	</header><!-- Header End -->


<div class="container-fluid">
    <nav class="navbar navbar-expand-lg bg-warning navbar-light text-dark py-lg-0 px-0"> 
        <div class="navbar-nav w-100 justify-content-center py-2">
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a class="text-dark font-weight-normal"href="{{ c.get_absolute_url }}"><strong>{{ c.name }}</strong></a>
                </li>
            {% endfor %}
        </div>
    </nav>
</div>



<div id="content">
    {% block content %}
    {% endblock content %}
</div>
<div>
    {% block main %}
    {% endblock main %}
</div>


</body>
</html>

shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% load static %}


{% block main %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" type="text/css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css" type="text/css" rel="stylesheet" />
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>

<div class="carousel pb-5">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active data-mdb-interval="10000" ">
            <img class="d-block w-100" src="{% static 'img/1.jpg' %}" alt="First slide">
                {% comment %} <div class="carousel-caption d-none d-md-block">
                    <h1 class="text-carousel"> НОВЕ НАДХОДЖЕННЯ </h1>
                <a href="{% url 'shop:product_list' %}" class="btn essence-btn">ПОДИВИТИСЯ НОВУ КОЛЕКЦІЮ</a>
                </div> {% endcomment %}
            </div>
            <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'img/2.jpg' %}" alt="Second slide">
                {% comment %} <div class="carousel-caption d-none d-md-block">
                    <h1 class="text-carousel"> НОВЕ НАДХОДЖЕННЯ </h1>
                <a href="{% url 'shop:product_list' %}" class="btn essence-btn">ПОДИВИТИСЯ НОВУ КОЛЕКЦІЮ</a>
                </div> {% endcomment %}
            </div>
            <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'img/3.jpg' %}" alt="Third slide">
                {% comment %} <div class="carousel-caption d-none d-md-block">
                    <h1 class="text-carousel"> НОВЕ НАДХОДЖЕННЯ </h1>
                <a href="{% url 'shop:product_list' %}" class="btn essence-btn">ПОДИВИТИСЯ НОВУ КОЛЕКЦІЮ</a>
                </div> {% endcomment %}
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div><div class="border-bottom">
    <div class="d-flex justify-content-center pt-5 border-bottom">
        <h5>Нові видання</h5>
    </div>
<div class="owl-carousel owl-theme pb-5">
    {% for item in top %}
        <div class="item pr-2 py-3">
            <a href="{{ item.get_absolute_url }}">
                <img src="{% if item.image %}
                    {{ item.image.url }}
                {% else %}
                    {% static 'img/no_image.png' %}    
                {% endif %}" alt="">
            </a>
            <a style="color:black;" href="{{ item.get_absolute_url}}">{{ item.name }}</a><br>
                {{ item.price }}грн.
        </div>
    {% endfor %}
</div>
</div>


<script>
$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    dots:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})
</script>

{% endblock main %}